### ISSUE TITLE
Learning from the first campaign, June 2017

### ISSUE THREAD

**Issue by couci** [MozillaIndia/RustIndia#15]
This is an issue we are gathering learning from the first campaign

1) Ask people to fork their modifications instead of simple PRs
2) Better org of the communication pipeline so we don't miss the numbers
3) Share more extensively the links that need to be used
4) Integrate better the 30daysofRust - find ways to track (new initiative)
5) More collaboration with the Rust team - building better bridges
6) Scale the campaign

**Comment by dvigneshwer** [comment]
Adding few more points to work on:

7. Train the trainers sessions to support mobilizers across different regions
8. Recruiting more people to be part of the core team
9. Improving womoz participation
