### ISSUE TITLE
how to do the rust game using this idea

### ISSUE THREAD

**Issue by tejalavu96** [MozillaIndia/RustIndia#22]
And I am having an idea of doing a game at first we will place a question so that if two different people approach the person who clicked first on the question he/she can ask question and if the answer is right then the person who asked the question will be killed else the other will be killed and the weapon and fight style was selected by him and like that he take his group flag and return to his flag or his room then they will get a point please help me in designing the game or send me the game code which is same like this so that i can modify or recreate the game using same gui

**Comment by dvigneshwer** [comment]
Check out the [piston crate](http://www.piston.rs/) & [arewegameyet](http://arewegameyet.com/) sites for sample game codes.

Best of luck implementing your game.
