### ISSUE TITLE
What drives rust developers

### ISSUE THREAD

**Issue by Tusharchoudhary** [MozillaIndia/RustIndia#24]
Is it selfless love for open source development that drives rust developers or there is some  vision I m not able to see

**Comment by dvigneshwer** [comment]
You should check out this [video](http://intorust.com/tutorial/why-rust/) which talks about the subject.

In short:

* Rust solves a lot of common system programming language
* Amazing & welcoming open community which learns mutually
* Provides a great ecosystem which facilitates faster development

**Comment by ranjithrajv** [comment]
This article might be interesting to you 
https://medium.com/mozilla-tech/why-rust-is-the-most-loved-language-by-developers-666add782563
