### ISSUE TITLE
Reach out to external stakeholders

### ISSUE THREAD

**Issue by couci** [MozillaIndia/RustIndia#6]
- [x] Share with Carol the plan for review @rowdymehul
- [x] Reach out to identified places @dvigneshwer @rowdymehul
- [x] Reach out to TS for availability @couci @dvigneshwer

**Comment by couci** [comment]
Waiting for Carol to reply on what has been sent, also she will review the teaching kits.
@All we need to document the places

**Comment by dvigneshwer** [comment]
#### Updates:

* Added questions to Rust community team in the campaign document
* We can reach out to the TS on their availability for offline and online events after we have the tentative event schedule

**Comment by nomadicmehul** [comment]
Updates : 

- Added place and dated in planning pad. 50% places are confirmed. 

- emailed Carol to review the plan.
