### ISSUE TITLE
Draft comms outreach

### ISSUE THREAD

**Issue by couci** [MozillaIndia/RustIndia#7]
- [x] Draft comms for campaign outreach in social media @prathameshchavan
- [x] Draft inner comms for reach out to Rust community @rowdymehul
- [x] Draft message for event organizers

**Comment by couci** [comment]
Mehul has already contacted organizers. To do:
- [x] document the people that have been contacted
- [x] Umesh to contact Bangalore people

Please document here: https://docs.google.com/document/d/1B63hURfeS1b5WEj6_tOBsiPyA7gAlhCh_mspuX5v-_U/edit#

**Comment by couci** [comment]
Prathamesh is writing the drafts for social media outreach and Mehul is leading the blogging part

**Comment by dvigneshwer** [comment]
We will also need to post these information in the Rust community Channels:

* blog.community.rs
* Rust discource

**Comment by couci** [comment]
Comms for launching have been drafted: https://docs.google.com/document/d/140kKhXoqCg3a3FisMpOnESVIvnpS5KSh-zGN1AsfSPs/edit?hl=en
Mehul has started keeping a record of spaces here: https://public.etherpad-mozilla.org/p/RainOfRust_Calender_June

**Comment by nomadicmehul** [comment]
Draft for Mozilla India blog is done. Soon to publish. 

+1 @dvigneshwer

**Comment by nomadicmehul** [comment]
Update : 

Trailer Draft published on : 

- [Mozilla India Blog ](https://blog.mozillaindia.org/1911)

- [Mozilla Discourse](https://discourse.mozilla-community.org/t/rainofrust-campaign-trailer/15852)   

- [Rust Discourse](https://users.rust-lang.org/t/rainofrust-campaign-trailer/10993)

**Comment by nomadicmehul** [comment]
Update: 

Created 3 reps page for offline events. you cam check here : https://public.etherpad-mozilla.org/p/RainOfRust_Calender_June

More will be post soon. 👍

**Comment by nomadicmehul** [comment]
For social media outreach, created this : https://ankit-k-singh.github.io/rainofrust/

This has been created by Nashik community member Ankit and getting a very good response.

**Comment by couci** [comment]
We need to post on reddit @rowdymehul

**Comment by dvigneshwer** [comment]
Also, we need to update in blog.community.rs - @dvigneshwer

**Comment by nomadicmehul** [comment]
Hey @couci sorry for posting late here.. already posted on reddit. 👍

**Comment by couci** [comment]
I think this is good to be closed

**Comment by tejalavu96** [comment]
may i know what do you clearly about my code ?
