### ISSUE TITLE
Budget and swag requests have been submitted

### ISSUE THREAD

**Issue by couci** [MozillaIndia/RustIndia#8]
- [x] Submit budget request based on potential spaces @umeshagarwal 
- [x] Open swag request on bugzilla @umeshagarwal 
- [x] Set dates for online events  @dvigneshwer 
- [x] Set dates for offline events @umeshagarwal

**Comment by dvigneshwer** [comment]
Updates:

* Added tentative dates and agenda for online events in the campaign document

**Comment by couci** [comment]
Dates for online and  events are here:https://discourse.mozilla-community.org/t/rainofrust-online-events-schedule/15970
More offline events will be added

**Comment by couci** [comment]
@rowdymehul to add more offline events

**Comment by nomadicmehul** [comment]
Offline event schedule : https://discourse.mozilla-community.org/t/rainofrust-offline-events-schedule/16038/2

**Comment by nomadicmehul** [comment]
@couci can we close this?

**Comment by couci** [comment]
yes its good to be closed
