### ISSUE TITLE
Consistent coding style needed

### ISSUE THREAD

**Issue by badboy** [MozillaIndia/RustIndia#9]
I only took a brief look at the [long demo code](https://github.com/MozillaIndia/RustIndia/tree/master/long_demo), but I saw multiple problems regarding coding style.
To teach best practices and make it easier for beginners it would be good to follow a clear, consistent coding style. That includes proper use of whitespacing, etc.

It would probably be a good idea to run [rustfmt](https://github.com/rust-lang-nursery/rustfmt) on the good and check the results.

**Comment by dvigneshwer** [comment]
Thanks for the feedback, will use the rustfmt tool and update the materilas accordingly.

**Comment by nomadicmehul** [comment]
Thanks for the feedback @badboy
